# Generated by Django 4.2.24 on 2025-11-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_has_ai_trainer_lessonmaterial_has_ai_trainer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitrainingsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия ИИ-тренажёра', 'verbose_name_plural': 'Сессии ИИ-тренажёров'},
        ),
        migrations.AddField(
            model_name='aitrainingsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='aitrainingsession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.CreateModel(
            name='AITrainerPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название промпта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('prompt_text', models.TextField(verbose_name='Текст промпта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to='courses.course', verbose_name='Курс (опционально)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to='courses.lesson', verbose_name='Урок (опционально)')),
            ],
            options={
                'verbose_name': 'Промпт для ИИ-тренажёра',
                'verbose_name_plural': 'Промпты для ИИ-тренажёров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aitrainingsession',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ai_trainer.aitrainerprompt', verbose_name='Использованный промпт'),
        ),
    ]
