# Generated by Django 4.2.24 on 2025-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_languagetest_surveyoption_surveyquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_questions/', verbose_name='Изображение к вопросу'),
        ),
    ]
