# Generated by Django 4.2.24 on 2025-10-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_achievement_badge_homework_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(help_text='Общая длительность курса', verbose_name='Длительность курса '),
        ),
    ]
