# Generated by Django 4.2.24 on 2025-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_ai_trainer',
            field=models.BooleanField(default=False, verbose_name='Есть ИИ-тренажер'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='has_ai_trainer',
            field=models.BooleanField(default=False, verbose_name='Есть ИИ-тренажер'),
        ),
    ]
