# Generated by Django 4.2.24 on 2025-11-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_trainer', '0002_alter_aitrainingsession_options_and_more'),
        ('courses', '0004_lesson_has_ai_trainer_lessonmaterial_has_ai_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmaterial',
            name='has_ai_trainer',
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='ai_trainer_prompt',
            field=models.ForeignKey(blank=True, help_text='Позволяет выбрать конкретный промпт для данного материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_trainer.aitrainerprompt', verbose_name='Промпт ИИ-тренажёра'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='ai_trainer_session',
            field=models.ForeignKey(blank=True, help_text='Выберите, если этот материал связан с конкретным AI тренажёром', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_trainer.aitrainingsession', verbose_name='Привязанный ИИ-тренажёр'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF документ'), ('doc', 'Документ'), ('ppt', 'Презентация'), ('video', 'Видео'), ('audio', 'Аудио'), ('image', 'Изображение'), ('link', 'Ссылка'), ('ai_trainer', 'ИИ-тренажёр')], max_length=20, verbose_name='Тип материала'),
        ),
    ]
