# Generated by Django 4.2.24 on 2025-09-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='Университет')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Специализация')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Лет опыта')),
                ('teaching_experience', models.TextField(blank=True, verbose_name='Опыт преподавания')),
                ('languages_spoken', models.JSONField(blank=True, default=list, verbose_name='Знание языков')),
                ('certificates', models.JSONField(blank=True, default=list, verbose_name='Сертификаты')),
                ('subjects', models.JSONField(blank=True, default=list, verbose_name='Предметы преподавания')),
                ('teaching_methods', models.TextField(blank=True, verbose_name='Методики преподавания')),
                ('available_hours', models.JSONField(blank=True, default=dict, verbose_name='Доступное время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Профиль преподавателя',
                'verbose_name_plural': 'Профили преподавателей',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=50, verbose_name='Уровень образования')),
                ('school', models.CharField(blank=True, max_length=255, verbose_name='Школа/Университет')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Класс/Курс')),
                ('native_language', models.CharField(default='Русский', max_length=50, verbose_name='Родной язык')),
                ('target_language', models.CharField(default='Английский', max_length=50, verbose_name='Целевой язык')),
                ('language_level', models.CharField(blank=True, choices=[('a1', 'A1 - Начальный'), ('a2', 'A2 - Элементарный'), ('b1', 'B1 - Средний'), ('b2', 'B2 - Выше среднего'), ('c1', 'C1 - Продвинутый'), ('c2', 'C2 - Владение на уровне носителя')], max_length=20, verbose_name='Уровень языка')),
                ('parent_name', models.CharField(blank=True, max_length=255, verbose_name='Имя родителя')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email родителя')),
                ('preferred_learning_time', models.CharField(blank=True, max_length=50, verbose_name='Предпочтительное время занятий')),
                ('learning_goals', models.TextField(blank=True, verbose_name='Цели обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('interested', 'Заинтересован'), ('demo_scheduled', 'Назначена демо-встреча'), ('demo_completed', 'Демо-встреча проведена'), ('proposal_sent', 'Отправлено предложение'), ('negotiation', 'Переговоры'), ('converted', 'Конвертирован'), ('lost', 'Потерян')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('social_media', 'Социальные сети'), ('referral', 'Реферал'), ('advertisement', 'Реклама'), ('event', 'Мероприятие'), ('other', 'Другое')], default='website', max_length=20, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конверсии')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначен менеджер')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Интересующий курс')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('student_performance', 'Успеваемость студентов'), ('teacher_performance', 'Эффективность преподавателей'), ('financial', 'Финансовая отчетность'), ('marketing', 'Маркетинговая отчетность'), ('operational', 'Операционная отчетность')], max_length=30, verbose_name='Тип отчета')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерирован пользователем')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Вход в систему'), ('lesson_attended', 'Посетил занятие'), ('lesson_missed', 'Пропустил занятие'), ('homework_submitted', 'Сдал домашнее задание'), ('homework_late', 'Сдал домашнее задание с опозданием'), ('payment_made', 'Сделал платеж'), ('feedback_given', 'Оставил отзыв'), ('support_request', 'Обратился в поддержку'), ('course_completed', 'Завершил курс')], max_length=30, verbose_name='Тип активности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Активность студента',
                'verbose_name_plural': 'Активности студентов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='crm_student_student_e5c64c_idx'), models.Index(fields=['activity_type', 'created_at'], name='crm_student_activit_d551bf_idx')],
            },
        ),
    ]
