# Generated by Django 4.2.24 on 2025-10-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='available_hours',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaching_experience',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaching_methods',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История зарплат (список записей: {"дата": "...", "сумма": ..., "тип": ...})'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('hour', 'В час'), ('day', 'В день'), ('month', 'В месяц')], default='hour', max_length=10, null=True, verbose_name='Тип зарплаты'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
