# Generated by Django 4.2.24 on 2025-10-02 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Шаблон уведомления', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Настройки уведомлений', 'verbose_name_plural': 'Настройки уведомлений'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='channels',
            field=models.JSONField(default=list, verbose_name='Каналы отправки'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channels',
            field=models.JSONField(default=list, verbose_name='Каналы отправки'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('lesson', 'Занятие'), ('payment', 'Платеж'), ('message', 'Сообщение'), ('system', 'Система'), ('course', 'Курс'), ('attendance', 'Посещаемость'), ('homework', 'Домашнее задание'), ('test', 'Тест'), ('feedback', 'Обратная связь'), ('support', 'Поддержка'), ('admin', 'Административное')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(default='Нет заголовка', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='email_support_responses',
            field=models.BooleanField(default=True, verbose_name='Ответы службы поддержки по email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='push_payment_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о платежах push'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='push_support_responses',
            field=models.BooleanField(default=True, verbose_name='Ответы службы поддержки push'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='sms_lesson_reminders',
            field=models.BooleanField(default=True, verbose_name='Напоминания о занятиях SMS'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='sms_payment_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о платежах SMS'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='telegram_lesson_reminders',
            field=models.BooleanField(default=True, verbose_name='Напоминания о занятиях в Telegram'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='telegram_payment_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о платежах в Telegram'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='whatsapp_lesson_reminders',
            field=models.BooleanField(default=True, verbose_name='Напоминания о занятиях в WhatsApp'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='whatsapp_payment_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о платежах в WhatsApp'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('lesson', 'Занятие'), ('payment', 'Платеж'), ('message', 'Сообщение'), ('system', 'Система'), ('course', 'Курс'), ('attendance', 'Посещаемость'), ('homework', 'Домашнее задание'), ('test', 'Тест'), ('feedback', 'Обратная связь'), ('support', 'Поддержка'), ('admin', 'Административное')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('lesson', 'Занятие'), ('payment', 'Платеж'), ('message', 'Сообщение'), ('system', 'Система'), ('course', 'Курс'), ('attendance', 'Посещаемость'), ('homework', 'Домашнее задание'), ('test', 'Тест'), ('feedback', 'Обратная связь'), ('support', 'Поддержка'), ('admin', 'Административное')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent'], name='notificatio_is_sent_254da2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_265656_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read_at'], name='notificatio_read_at_6329f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'created_at'], name='notificatio_notific_28445a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_a3de53_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_8fa9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_dbd4df_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_d19621_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['read_at'], name='notificatio_read_at_e7f1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['name'], name='notificatio_name_05069a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_d9e94e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['created_at'], name='notificatio_created_e605d6_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['user'], name='notificatio_user_id_a14c99_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['email_notifications'], name='notificatio_email_n_7d7518_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['push_notifications'], name='notificatio_push_no_44b874_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['telegram_notifications'], name='notificatio_telegra_42b5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['whatsapp_notifications'], name='notificatio_whatsap_5f6697_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['sms_notifications'], name='notificatio_sms_not_c18b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['created_at'], name='notificatio_created_008308_idx'),
        ),
    ]
